[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Billy Weisberg <billy@energyapps.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
